import os.path
#-----------------------------------------------------------------------------
# Brio/System/Camera
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

module_name	= 'Camera'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
modsrcs		= FindModuleSources(Dir('.'), vars)
mpisrcs		= FindMPISources(Dir('.'), vars)
modlibs		= ['AudioMPI', 'DisplayMPI', 'EventMPI', 'KernelMPI', 
					 'DebugMPI', 'jpeg', 'asound', 'sndfile']
mpilibs		= ['ModuleMPI']

#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()

myenv.Append(CPPPATH = ['#ThirdParty/LibJPEG/Include'])
myenv.Append(CPPPATH = ['#ThirdParty/LibSndFile/Include'])

myenv.Append(LIBPATH = ['#ThirdParty/LibJPEG/Libs/' + vars['cpu_subdir']])
myenv.Append(LIBPATH = ['#ThirdParty/LibSndFile/Libs/' + vars['cpu_subdir']])

rootfs = os.getenv('ROOTFS_PATH')
myenv.Append(LIBPATH = [os.path.join(rootfs, 'usr', 'lib')])

mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, kBuildModule, vars)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(module_name, [], mpilibs +  ['DisplayMPI', 'EventMPI', 'AudioMPI', 'KernelMPI', 'VideoMPI'], myenv, vars)

Return('mymodule', 'mympi')
