"""
This data folder holds files that normally would be installed through the PCApp.
At the time this example is being put together, the PCApp is not complete.
"""

import os
import glob
import CoreTools.CopyTree

Import(['env_vars', 'env'])
myEnv = env.Clone()     #clone this, so we're not changing the original
tld = env_vars['tld']

# CYO
# Yes, this has CYO in the path twice.  Thus saith the docs. <atc> The docs hath been changeth
myResources = CoreTools.CopyTree.CopyTree(myEnv, 'cyo', 
							os.path.join(env_vars['data_deploy_dir'], 'CYO', tld))
# MDLs
myResources.extend(CoreTools.CopyTree.CopyTree(myEnv, 'mdl', 
							os.path.join(env_vars['data_deploy_dir'], 'MDL')))
# Avatars
myResources.extend(CoreTools.CopyTree.CopyTree(myEnv, 'avatars', 
							os.path.join(env_vars['data_deploy_dir'], 'Avatars')))

myEnv.Default(myResources)
