import os

#-----------------------------------------------------------------------------
# Brio/System/Button
#-----------------------------------------------------------------------------
Import('*')

module_name	= 'Button'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
emulibs		= local_vars['is_emulation'] and ['X11'] or []
modsrcs		= FindModuleSources(Dir('.'))
mpisrcs		= FindMPISources(Dir('.'))
modlibs		= ['DebugMPI', 'EventMPI', 'KernelMPI'] + emulibs
mpilibs		= ['ModuleMPI']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
if os.getenv('EXTRA_LINUX_HEADER_DIR') == None:
	extinc      = '#../LinuxDist/packages/drivers/include/linux'
	print "EXTRA_LINUX_HEADER_DIR not defined.  Using default."
else:
	extinc      = os.getenv('EXTRA_LINUX_HEADER_DIR')

if local_vars['is_emulation'] == 0:
	myenv.Append(CPPPATH = [extinc])

mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, 0)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, 1)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(module_name, [], mpilibs + ['EventMPI'] + emulibs, myenv)

Return('mymodule', 'mympi')
