#-----------------------------------------------------------------------------
# Brio/System/Button
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

module_name	= 'Button'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
emulibs		= vars['is_emulation'] and ['X11'] or []
modsrcs		= FindModuleSources(Dir('.'), vars)
mpisrcs		= FindMPISources(Dir('.'), vars)
mpilibs		= ['Utility']
if vars['is_emulation']:
	mpisrcs = mpisrcs + modsrcs
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
if not vars['is_publish']:
	RunMyTests(module_name, [], mpilibs + ['EventMPI'] + emulibs, myenv, vars)

Return('mympi')
