#-----------------------------------------------------------------------------
# Brio/System/Module
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

module_name = 'Module'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
emulib		= vars['is_emulation'] and ['Emulation'] or []
modsrcs		= FindModuleSources(Dir('.'), vars)
mpisrcs		= FindMPISources(Dir('.'), vars)
modlibs		= emulib
mpilibs		= emulib
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, kBuildModule, vars)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(module_name, [], mpilibs, myenv, vars)

Return('mymodule', 'mympi')
