#-----------------------------------------------------------------------------
# Brio/LightningGCC Repository
#-----------------------------------------------------------------------------
import os.path
import glob
Import('*')

#-----------------------------------------------------------------------------
# Populate the "Publish" folder for a public release
#-----------------------------------------------------------------------------
if local_vars['is_publish']:
	samples = ['Simple', 'BrioCube', 'Button', 'Display']
	dest_dir = os.path.join(local_vars['publish_root'], 'Samples')
	for s in samples:
		Command( os.path.join(dest_dir, s), os.path.join('Samples', s), 
				Copy("$TARGET", "$SOURCE"))
	env.Install(local_vars['publish_root'], 'readme.txt')
	env.Install(local_vars['publish_root'], 'ReleaseNotes.txt')
	
