#-----------------------------------------------------------------------------
# Brio/Lightning Repository
#-----------------------------------------------------------------------------
import os.path
import glob
Import('*')

#-----------------------------------------------------------------------------
# Populate the "Publish" folder for a public release
#-----------------------------------------------------------------------------
if vars['is_publish'] and vars['is_export']:
	samples = ['Simple', 'BrioCube', 'BrioAudio', 'Button', 'Display', 'BrioVideo']
	dest_dir = os.path.join(vars['export_root'], 'Samples')
	for s in samples:
		Command( os.path.join(dest_dir, s), os.path.join('Samples', s), 
				Copy("$TARGET", "$SOURCE"))
	env.Install(vars['export_root'], 'readme.txt')
	env.Install(vars['export_root'], 'ReleaseNotes.txt')
	
