#-----------------------------------------------------------------------------
# Brio/System/Utility
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
import os

Import('env')

mpi_name = 'Utility'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
mpisrcs		= Glob('*.cpp')
mpilibs		= []
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Clone()
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI)

targets = mympi or []

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
if env['buildtests']:
	if env['cpu'] != 'x86':
		targets.append(RunMyTests(mpi_name, [], mpilibs + ['DebugMPI', 'KernelMPI'], myenv))
	else:
		print "WARNING: Utility test disabled in emulation until fixed!"

Return('targets')
