#=============================================================================
# Top level SConstruct file for the SCons build system
#
# Quick tour of SCons:
#
#   SCons is a build tool that replaces "make" functionality.
#   It executes as a Python script, which gives you the full power
#   of the Python scripting language in defining build steps.
#
#=============================================================================


import EnvTargets

tld = 'CameraDemo'

#Get environments dictionary
environments = EnvTargets.GetStdEnvironments(ARGUMENTS, tld)
environments = EnvTargets.GetStdEnvironments(ARGUMENTS, tld, app_type='Leaplet', lfplatform='Rio')

#Include LFOS SDK
EnvTargets.IncludeSDK(environments, ARGUMENTS)

for target, env in environments.iteritems():
	Export('env')
	print env['variant_dir']
	SConscript('SConscript', variant_dir = env['variant_dir'], duplicate=0)

EnvTargets.CreateTargets(environments)

