"""
SConscript file.
"""

import os
import CopyTree

Import('env')
myEnv = env.Clone()     #clone this, so we're not changing the original

appname = 'CameraDemo'

if env['cpu']:
	#global libs
	sources = Glob(os.path.join('*.cpp')) #this should get everything in subdirectories
	
	# Set up targets
	myEnv.Append(CPPPATH = ['Include'])
	myEnv.Append(CPPDEFINES = ['USTRING'])
	myEnv.Replace(LIBS = ['ModuleMPI', 'DebugMPI', 'KernelMPI', 'EventMPI', 'dl', 'pthread', 'ustring', 'iconv', 'intl'])
	myEnv.Append(LIBS = ['CameraMPI', 'DisplayMPI', 'ButtonMPI'])	

	myResources = CopyTree.CopyTree(myEnv, Dir(os.path.join('#', 'apprsrc')).abspath, env['install_dir'].abspath)
	#myModule = myEnv.SharedLibrary(os.path.join(env['install_dir'].abspath, libname), sources, SHLIBPREFIX='')
	myModule = myEnv.Program(appname, sources)
	env['targets'] += env.Install( env['install_dir'], myModule)
	env['targets'] += myResources

