#-----------------------------------------------------------------------------
# Brio/System/Audio
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *

import os.path
Import('*')

module_name	= 'Audio'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
modsrcs		= FindModuleSources(Dir('.'), vars)
mpisrcs		= FindMPISources(Dir('.'), vars)
modlibs		= ['KernelMPI', 'DebugMPI', 'EventMPI', 
				'portaudio', 'pthread', 'vorbisidec', 'dsputil', 'sndfile', 'Utility']
mpilibs		= ['ModuleMPI', 'KernelMPI', 'DebugMPI']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module

#-----------------------------------------------------------------------------
myenv		= env.Copy()

myenv.Append(CPPPATH = ['#ThirdParty/Portaudio/Include'])
myenv.Append(CPPPATH = ['#ThirdParty/Mobileer/spmidi/include'])
myenv.Append(CPPPATH = ['#ThirdParty/Mobileer'])
#myenv.Append(CPPPATH = ['#ThirdParty/Mobileer/Source'])
myenv.Append(CPPPATH = ['#ThirdParty/Theora/Include'])
myenv.Append(CPPPATH = ['#System/Audio/DspUtil'])
myenv.Append(CPPPATH = ['#System/Audio/LibSndFile'])

if vars['is_emulation']:
	myenv.Append(RPATH   = [myenv.Dir('#ThirdParty/Portaudio/Libs/x86').abspath, myenv.Dir('#ThirdParty/Mobileer/Libs/x86').abspath, myenv.Dir('#ThirdParty/Theora/Libs/x86').abspath])

myenv.Append(LIBPATH = ['#ThirdParty/Portaudio/Libs/' + vars['cpu_subdir']])
myenv.Append(LIBPATH = ['#ThirdParty/Mobileer/Libs/' + vars['cpu_subdir']])
myenv.Append(LIBPATH = ['#ThirdParty/Theora/Libs/' + vars['cpu_subdir']])
myenv.Append(LIBPATH = ['#System/Audio/DspUtil/' + vars['cpu_subdir']])
myenv.Append(LIBPATH = ['#System/Audio/LibSndFile/' + vars['cpu_subdir']])

mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, kBuildModule, vars)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
if not vars['is_publish']:
	RunMyTests(module_name, [], mpilibs + ['EventMPI'], myenv, vars)

Return('mymodule', 'mympi')
