#-----------------------------------------------------------------------------
# Brio/System/Audio
#-----------------------------------------------------------------------------
Import('*')

module_name	= 'Audio'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
modsrcs		= FindModuleSources(Dir('.'))
mpisrcs		= FindMPISources(Dir('.'))
modlibs		= ['KernelMPI', 'DebugMPI', 'portaudio', 'alsatoss']
mpilibs		= ['ModuleMPI', 'KernelMPI']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
myenv.Append(CPPPATH = ['#ThirdParty/Portaudio/Include'])
myenv.Append(LIBPATH = ['#ThirdParty/Portaudio/Libs'])
mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, 0)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, 1)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(module_name, [], mpilibs + ['EventMPI'], myenv)

Return('mymodule', 'mympi')
