#-----------------------------------------------------------------------------
# Brio/System/Video
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

module_name	= 'Video'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
modsrcs		= FindModuleSources(Dir('.'), vars)
mpisrcs		= FindMPISources(Dir('.'), vars)
modlibs		= ['DebugMPI', 'SystemResourceMPI', 'ogg', 'theora']
mpilibs		= ['ModuleMPI']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
myenv.Append(CPPPATH = ['#ThirdParty/Theora/Include'])
# Distinguish x86 vs ARM library binaries
if vars['is_emulation']:
	myenv.Append(LIBPATH = ['#ThirdParty/Theora/Libs/x86'])
	myenv.Append(RPATH   = myenv.Dir('#ThirdParty/Theora/Libs/x86').abspath)
else:
	myenv.Append(LIBPATH = ['#ThirdParty/Theora/Libs/arm'])
						
mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, kBuildModule, vars)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(module_name, [], mpilibs +  ['ResourceMPI'], myenv, vars)

Return('mymodule', 'mympi')
