#-----------------------------------------------------------------------------
# Brio/System Repository
#-----------------------------------------------------------------------------
import os.path
Import('*')

#-----------------------------------------------------------------------------
# Create the folder name for a module's intermediate files
#-----------------------------------------------------------------------------
def MakeTempDirName(module):
	return os.path.join(local_vars['intermediate_build_dir'], module)
 

#-----------------------------------------------------------------------------
# Invoke individual module builders
#-----------------------------------------------------------------------------
audio	= SConscript('Audio/SConscript', build_dir=MakeTempDirName('Audio'), duplicate=0)
button	= SConscript('Button/SConscript', build_dir=MakeTempDirName('Button'), duplicate=0)
debug	= SConscript('Debug/SConscript', build_dir=MakeTempDirName('Debug'), duplicate=0)
event	= SConscript('Event/SConscript', build_dir=MakeTempDirName('Event'), duplicate=0)
kernel	= SConscript('Kernel/SConscript', build_dir=MakeTempDirName('Kernel'), duplicate=0)
module	= SConscript('Module/SConscript', build_dir=MakeTempDirName('Module'), duplicate=0)
resource	= SConscript('Resource/SConscript', build_dir=MakeTempDirName('Resource'), duplicate=0)


#-----------------------------------------------------------------------------
# Populate the "Publish" folder for a public release
#-----------------------------------------------------------------------------
if local_vars['is_publish']:
	env.Install('Publish', Dir('Include'))
#	env.Install('Publish', audio)
	