Brio2: CKernelMPI Class Reference
CKernelMPI Class Reference
#include <KernelMPI.h>
Inherits ICoreMPI.
Public Member Functions
virtual Boolean IsValid () const
virtual const CString * GetMPIName () const
virtual tVersion GetModuleVersion () const
virtual const CString * GetModuleName () const
virtual const CURI * GetModuleOrigin () const
CKernelMPI ()
virtual ~CKernelMPI ()
tErrType CreateTask (tTaskHndl &hndl, const tTaskProperties &properties, const char *pDebugName=NULL)
Tasks.
tErrType JoinTask (tTaskHndl hndl, tPtr &threadReturnValue)
tErrType CancelTask (tTaskHndl hndl)
Requests that thread be canceled.
tTaskHndl GetCurrentTask () const
Returns the thread ID of the calling thread.
int GetTaskPriority (tTaskHndl hndl) const
Gets the task priority of the thread given by thread.
int GetTaskSchedulingPolicy (tTaskHndl hndl) const
Gets the scheduling parameter of the thread given by thread.
void TaskSleep (U32 msec) const
tPtr Malloc (U32 size)
Memory Allocation.
void Free (tPtr pAllocatedMemory)
tErrType OpenMessageQueue (tMessageQueueHndl &hndl, const tMessageQueuePropertiesPosix &props, const char *pDebugName=NULL)
tErrType CloseMessageQueue (tMessageQueueHndl hndl, const tMessageQueuePropertiesPosix &props)
Closes the message queue, invalidating hndl.
tErrType ClearMessageQueue (tMessageQueueHndl hndl)
Clears message Queue.
int GetMessageQueueNumMessages (tMessageQueueHndl hndl) const
Gets the the current number of messages.
tErrType SendMessage (tMessageQueueHndl hndl, const CMessage &msg)
Adds the message pointed to by hndl to the message queue.
tErrType SendMessageOrWait (tMessageQueueHndl hndl, const CMessage &msg, U32 timeoutMs=kMaxTimeoutMs)
tErrType ReceiveMessage (tMessageQueueHndl hndl, CMessage *msg, U32 maxMessageSize)
tErrType ReceiveMessageOrWait (tMessageQueueHndl hndl, CMessage *msg, U32 maxMessageSize, U32 timeoutMs=kMaxTimeoutMs)
U32 GetElapsedTimeAsMSecs () const
Elapsed time in milliseconds since the Epoch (1970). (32-bit wrap-around)
U64 GetElapsedTimeAsUSecs () const
Elapsed time in microseconds since the Epoch.
tErrType GetHRTAsUsec (U32 &uSec) const
Get time as microseconds from High Resolution Timer (HRT)
tErrType GetElapsedAsSec (U32 &sec) const
Get Elapsed time in seconds.
tErrType GetElapsedTimeAsStructure (Current_Time &curTime) const
Get Elapsed time as Current_Time structure.
tTimerHndl CreateTimer (pfnTimerCallback callback, const tTimerProperties &props, const char *pDebugName=NULL)
tErrType DestroyTimer (tTimerHndl hndl)
Deletes the timer created by CreateTimer()
tErrType ResetTimer (tTimerHndl hndl, const tTimerProperties &props)
Resets timer.
tErrType StartTimer (tTimerHndl hndl, const tTimerProperties &props)
Start the timer with parameters defined in the tTimerProperties property.
tErrType StopTimer (tTimerHndl hndl)
Turns off the timer.
tErrType PauseTimer (tTimerHndl hndl, saveTimerSettings &saveValue)
Pauses the timer.
tErrType ResumeTimer (tTimerHndl hndl, saveTimerSettings &saveValue)
tErrType GetTimerElapsedTime (tTimerHndl hndl, U32 *pMs, U32 *pUs=NULL) const
tErrType GetTimerRemainingTime (tTimerHndl hndl, U32 *pMs, U32 *pUs=NULL) const
tErrType StartWatchdog (U32 seconds) const
tErrType StopWatchdog (void) const
tErrType KeepWatchdogAlive (void) const
tErrType InitMutexAttributeObject (tMutexAttr &mutexAttr)
Initialize a mutex Attribute Object.
tErrType InitMutex (tMutex &mutex, const tMutexAttr &mutexAttr)
Initializes a mutex with the attributes specified in the specified mutex attribute object.
tErrType DeInitMutex (tMutex &mutex)
Destroys a mutex.
S32 GetMutexPriorityCeiling (const tMutex &mutex) const
Obtains the priority ceiling of a mutex attribute object.
tErrType SetMutexPriorityCeiling (tMutex &mutex, S32 prioCeiling, S32 *pOldPriority=NULL)
Sets the priority ceiling attribute of a mutex attribute object.
tErrType LockMutex (tMutex &mutex)
Locks an unlocked mutex.
tErrType TryLockMutex (tMutex &mutex)
Tries to lock a not tested.
tErrType UnlockMutex (tMutex &mutex)
Unlocks a mutex.
tErrType BroadcastCond (tCond &cond)
Unblocks all threads that are waiting on a condition variable.
tErrType DestroyCond (tCond &cond)
Destroys a condition variable attribute object.
tErrType InitCond (tCond &cond, const tCondAttr &attr)
tErrType SignalCond (tCond &cond)
Unblocks at least one thread waiting on a condition variable.
tErrType TimedWaitOnCond (tCond &cond, tMutex &mutex, const tTimeSpec *pAbstime)
tErrType WaitOnCond (tCond &cond, tMutex &mutex)
Automatically unlocks the specified mutex, and places the calling thread into a wait state.
tErrType DestroyCondAttr (tCondAttr &attr)
Destroys a condition variable.
tErrType GetCondAttrPShared (const tCondAttr &attr, int *pShared)
Obtains the process-shared setting of a condition variable attribute object.
tErrType InitCondAttr (tCondAttr &attr)
Initializes a condition variable attribute object.
tErrType SetCondAttrPShared (tCondAttr *pAttr, int shared)
void Printf (const char *formatString,...) const
Standard printf syntax to output a string through the serial port.
void VPrintf (const char *formatString, va_list arguments) const
Standard vprintf syntax to output a string through the serial port.
void PowerDown () const
std::vector< CPath > GetFilesInDirectory (const CPath &dir) const
Boolean IsDirectory (const CPath &dir) const
tHndl LoadModule (const CPath &dir) const
tHndl LoadModule (const CPath &dir, const int flags) const
void * RetrieveSymbolFromModule (tHndl obj, const CString &symbol) const
void UnloadModule (tHndl obj) const
tMemoryPoolHndl CreateMemPool (U32 size)
Memory Pool Allocation functions.
void DestroyMemPool (tMemoryPoolHndl pool)
tPtr MemPoolMalloc (tMemoryPoolHndl pool, U32 size)
tPtr MemPoolRealloc (tMemoryPoolHndl pool, tPtr pmem, U32 size)
void MemPoolFree (tMemoryPoolHndl pool, tPtr pmem)
Public Member Functions inherited from ICoreMPI
ICoreMPI ()
virtual ~ICoreMPI ()
Detailed Description
Definition at line 24 of file KernelMPI.h.
Constructor & Destructor Documentation
CKernelMPI::CKernelMPI ()
virtual CKernelMPI::~CKernelMPI () virtual
Member Function Documentation
tErrType CKernelMPI::BroadcastCond (tCond & cond)
Unblocks all threads that are waiting on a condition variable.
==============================================================================
Conditions
tErrType CKernelMPI::CancelTask (tTaskHndl hndl)
Requests that thread be canceled.
tErrType CKernelMPI::ClearMessageQueue (tMessageQueueHndl hndl)
Clears message Queue.
tErrType CKernelMPI::CloseMessageQueue (tMessageQueueHndl hndl, const tMessageQueuePropertiesPosix & props)
Closes the message queue, invalidating hndl.
tMemoryPoolHndl CKernelMPI::CreateMemPool (U32 size)
Memory Pool Allocation functions.
Create memory pool of size bytes and returns a pointer to the memory pool
Parameters
size initial size of memory pool in bytes
Returns
memory pool handle
tErrType CKernelMPI::CreateTask (tTaskHndl & hndl, const tTaskProperties & properties, const char * pDebugName = NULL)
Tasks.
Creates a new thread which starts executing at the routine function
tTimerHndl CKernelMPI::CreateTimer (pfnTimerCallback callback, const tTimerProperties & props, const char * pDebugName = NULL)
======================================================
Timer
Creates a per-process timer using CLOCK_REALTIME as a base.
Referenced by COneShotTimer::COneShotTimer().
tErrType CKernelMPI::DeInitMutex (tMutex & mutex)
Destroys a mutex.
tErrType CKernelMPI::DestroyCond (tCond & cond)
Destroys a condition variable attribute object.
tErrType CKernelMPI::DestroyCondAttr (tCondAttr & attr)
Destroys a condition variable.
void CKernelMPI::DestroyMemPool (tMemoryPoolHndl pool)
Destroys memory pool and releases all associated memory for that pool
Parameters
pool memory pool handle
tErrType CKernelMPI::DestroyTimer (tTimerHndl hndl)
Deletes the timer created by CreateTimer()
Referenced by COneShotTimer::~COneShotTimer().
void CKernelMPI::Free (tPtr pAllocatedMemory)
Frees the memory space pointed to by pAllocatedMemory, which has been returned by a previous call to Malloc
tErrType CKernelMPI::GetCondAttrPShared (const tCondAttr & attr, int * pShared)
Obtains the process-shared setting of a condition variable attribute object.
tTaskHndl CKernelMPI::GetCurrentTask () const
Returns the thread ID of the calling thread.
tErrType CKernelMPI::GetElapsedAsSec (U32 & sec) const
Get Elapsed time in seconds.
U32 CKernelMPI::GetElapsedTimeAsMSecs () const
Elapsed time in milliseconds since the Epoch (1970). (32-bit wrap-around)
==============================================================================
Time & Date
tErrType CKernelMPI::GetElapsedTimeAsStructure (Current_Time & curTime) const
Get Elapsed time as Current_Time structure.
U64 CKernelMPI::GetElapsedTimeAsUSecs () const
Elapsed time in microseconds since the Epoch.
std::vector<CPath> CKernelMPI::GetFilesInDirectory (const CPath & dir) const
==============================================================================
File System Functions
tErrType CKernelMPI::GetHRTAsUsec (U32 & uSec) const
Get time as microseconds from High Resolution Timer (HRT)
int CKernelMPI::GetMessageQueueNumMessages (tMessageQueueHndl hndl) const
Gets the the current number of messages.
virtual const CString* CKernelMPI::GetModuleName () const virtual
Implements ICoreMPI.
virtual const CURI* CKernelMPI::GetModuleOrigin () const virtual
Implements ICoreMPI.
virtual tVersion CKernelMPI::GetModuleVersion () const virtual
Implements ICoreMPI.
virtual const CString* CKernelMPI::GetMPIName () const virtual
Implements ICoreMPI.
S32 CKernelMPI::GetMutexPriorityCeiling (const tMutex & mutex) const
Obtains the priority ceiling of a mutex attribute object.
int CKernelMPI::GetTaskPriority (tTaskHndl hndl) const
Gets the task priority of the thread given by thread.
int CKernelMPI::GetTaskSchedulingPolicy (tTaskHndl hndl) const
Gets the scheduling parameter of the thread given by thread.
tErrType CKernelMPI::GetTimerElapsedTime (tTimerHndl hndl, U32 * pMs, U32 * pUs = NULL) const
Returns the amount of time after the last timer expiration as millisecond and microseconds
Referenced by COneShotTimer::GetTimerElapsedTimeInMilliSec().
tErrType CKernelMPI::GetTimerRemainingTime (tTimerHndl hndl, U32 * pMs, U32 * pUs = NULL) const
Returns the amount of time before the timer expires as millisecond and microseconds
Referenced by COneShotTimer::GetTimerRemainingTimeInMilliSec().
tErrType CKernelMPI::InitCond (tCond & cond, const tCondAttr & attr)
Initializes a condition variable with the attributes specified in the specified condition variable attribute object
tErrType CKernelMPI::InitCondAttr (tCondAttr & attr)
Initializes a condition variable attribute object.
tErrType CKernelMPI::InitMutex (tMutex & mutex, const tMutexAttr & mutexAttr)
Initializes a mutex with the attributes specified in the specified mutex attribute object.
tErrType CKernelMPI::InitMutexAttributeObject (tMutexAttr & mutexAttr)
Initialize a mutex Attribute Object.
==============================================================================
Mutexes
Boolean CKernelMPI::IsDirectory (const CPath & dir) const
virtual Boolean CKernelMPI::IsValid () const virtual
Implements ICoreMPI.
tErrType CKernelMPI::JoinTask (tTaskHndl hndl, tPtr & threadReturnValue)
Suspends execution of the calling thread until the target thread completes its execution.
tErrType CKernelMPI::KeepWatchdogAlive (void) const
tHndl CKernelMPI::LoadModule (const CPath & dir) const
==============================================================================
Code Module Functions
tHndl CKernelMPI::LoadModule (const CPath & dir, const int flags) const
tErrType CKernelMPI::LockMutex (tMutex & mutex)
Locks an unlocked mutex.
tPtr CKernelMPI::Malloc (U32 size)
Memory Allocation.
Allocates size bytes and returns a pointer to the allocated memory
void CKernelMPI::MemPoolFree (tMemoryPoolHndl pool, tPtr pmem)
Frees the memory pointed to by pAllocatedMemory allocated from pool
Parameters
pool memory pool handle
pmem pointer to memory returned by MemPoolMalloc() or MemPoolRealloc()
tPtr CKernelMPI::MemPoolMalloc (tMemoryPoolHndl pool, U32 size)
Allocates size bytes from pool and returns a pointer to the allocated memory
Parameters
pool memory pool handle
size size of allocation in bytes
Returns
pointer to memory allocated within pool
tPtr CKernelMPI::MemPoolRealloc (tMemoryPoolHndl pool, tPtr pmem, U32 size)
Re-Allocates size bytes from pool and returns a pointer to the allocated memory
Parameters
pool memory pool handle
pmem pointer to memory returned by MemPoolMalloc()
size size of allocation in bytes
Returns
pointer to memory allocated within pool
tErrType CKernelMPI::OpenMessageQueue (tMessageQueueHndl & hndl, const tMessageQueuePropertiesPosix & props, const char * pDebugName = NULL)
==============================================================================
Message Queues
Associates a message queue descriptor with the message queue specified by name. name uniquely identifies the message queue across the system.
tErrType CKernelMPI::PauseTimer (tTimerHndl hndl, saveTimerSettings & saveValue)
Pauses the timer.
Referenced by COneShotTimer::Pause().
void CKernelMPI::PowerDown () const
==============================================================================
Power Control Functions
void CKernelMPI::Printf (const char * formatString, ...) const
Standard printf syntax to output a string through the serial port.
==============================================================================
I/O Functions
tErrType CKernelMPI::ReceiveMessage (tMessageQueueHndl hndl, CMessage * msg, U32 maxMessageSize)
Copies the oldest of the highest priority messages into the buffer pointed to by msg_ptr and removes it from the queue
tErrType CKernelMPI::ReceiveMessageOrWait (tMessageQueueHndl hndl, CMessage * msg, U32 maxMessageSize, U32 timeoutMs = kMaxTimeoutMs)
behaves just like ReceiveMessage(), except that if the queue is empty and the O_NONBLOCK flag is not enabled for the message queue description, then timeoutMs specifies a ceiling on the time for which the call will block
tErrType CKernelMPI::ResetTimer (tTimerHndl hndl, const tTimerProperties & props)
Resets timer.
tErrType CKernelMPI::ResumeTimer (tTimerHndl hndl, saveTimerSettings & saveValue)
Resume the timer/// Returns the amount of time before the timer expires as millisecond and microseconds
Referenced by COneShotTimer::Resume().
void* CKernelMPI::RetrieveSymbolFromModule (tHndl obj, const CString & symbol) const
tErrType CKernelMPI::SendMessage (tMessageQueueHndl hndl, const CMessage & msg)
Adds the message pointed to by hndl to the message queue.
tErrType CKernelMPI::SendMessageOrWait (tMessageQueueHndl hndl, const CMessage & msg, U32 timeoutMs = kMaxTimeoutMs)
behaves just like SendMessage(), except that if the queue is full and the O_NONBLOCK flag is not enabled for the message queue description, then timeoutMs specifies a ceiling on the time for which the call will block
tErrType CKernelMPI::SetCondAttrPShared (tCondAttr * pAttr, int shared)
Sets the process-shared attribute in a condition variable attribute object to either PTHREAD_PROCESS_SHARED or PTHREAD_PROCESS_PRIVATE
tErrType CKernelMPI::SetMutexPriorityCeiling (tMutex & mutex, S32 prioCeiling, S32 * pOldPriority = NULL)
Sets the priority ceiling attribute of a mutex attribute object.
tErrType CKernelMPI::SignalCond (tCond & cond)
Unblocks at least one thread waiting on a condition variable.
tErrType CKernelMPI::StartTimer (tTimerHndl hndl, const tTimerProperties & props)
Start the timer with parameters defined in the tTimerProperties property.
Referenced by COneShotTimer::Start().
tErrType CKernelMPI::StartWatchdog (U32 seconds) const
==============================================================================
Watchdog Timer
tErrType CKernelMPI::StopTimer (tTimerHndl hndl)
Turns off the timer.
tErrType CKernelMPI::StopWatchdog (void) const
void CKernelMPI::TaskSleep (U32 msec) const
Causes the caller to sleep for at least the amount of time specified in duration
tErrType CKernelMPI::TimedWaitOnCond (tCond & cond, tMutex & mutex, const tTimeSpec * pAbstime)
Automatically unlocks the specified mutex, and places the calling thread into a wait state FIXME: pAbstime var
tErrType CKernelMPI::TryLockMutex (tMutex & mutex)
Tries to lock a not tested.
void CKernelMPI::UnloadModule (tHndl obj) const
tErrType CKernelMPI::UnlockMutex (tMutex & mutex)
Unlocks a mutex.
void CKernelMPI::VPrintf (const char * formatString, va_list arguments) const
Standard vprintf syntax to output a string through the serial port.
tErrType CKernelMPI::WaitOnCond (tCond & cond, tMutex & mutex)
Automatically unlocks the specified mutex, and places the calling thread into a wait state.
The documentation for this class was generated from the following file:
System/Include/KernelMPI.h