Brio2: EFdWrapper Class Reference
EFdWrapper Class Reference
#include <Wrappers.h>
Public Member Functions
EFdWrapper (int fd=-1)
EFdWrapper (const std::string &strFile, int oflag, int pmode=S_IWRITE)
~EFdWrapper ()
bool Open (const std::string &strFile, int oflag, int pmode=S_IWRITE)
void Close ()
void Assign (int fd)
bool IsValid ()
operator int ()
Detailed Description
Definition at line 13 of file Wrappers.h.
Constructor & Destructor Documentation
EFdWrapper::EFdWrapper (int fd = -1) inline
Definition at line 40 of file Wrappers.h.
Referenced by operator int().
EFdWrapper::EFdWrapper (const std::string & strFile, int oflag, int pmode = S_IWRITE) inline
Definition at line 45 of file Wrappers.h.
References Open().
EFdWrapper::~EFdWrapper () inline
Definition at line 55 of file Wrappers.h.
References Close().
Member Function Documentation
void EFdWrapper::Assign (int fd) inline
Definition at line 26 of file Wrappers.h.
References Close().
void EFdWrapper::Close () inline
Definition at line 78 of file Wrappers.h.
Referenced by Assign(), Open(), and ~EFdWrapper().
bool EFdWrapper::IsValid () inline
Definition at line 27 of file Wrappers.h.
Referenced by Open().
bool EFdWrapper::Open (const std::string & strFile, int oflag, int pmode = S_IWRITE) inline
Definition at line 64 of file Wrappers.h.
References Close(), and IsValid().
Referenced by EFdWrapper().
EFdWrapper::operator int () inline
Definition at line 28 of file Wrappers.h.
References EFdWrapper().
The documentation for this class was generated from the following file:
System/Include/Wrappers.h