Brio2: COneShotTimer Class Reference
COneShotTimer Class Reference
#include <Timer.h>
Public Member Functions
COneShotTimer (const tTimerProperties &props)
~COneShotTimer ()
tTimerHndl GetTimerHndl () const
void Start (const tTimerProperties &props)
void Pause (saveTimerSettings &saveValue)
void Resume (saveTimerSettings &saveValue)
tErrType GetTimerElapsedTimeInMilliSec (U32 *ms) const
tErrType GetTimerRemainingTimeInMilliSec (U32 *ms) const
Detailed Description
Definition at line 69 of file Timer.h.
Constructor & Destructor Documentation
COneShotTimer::COneShotTimer (const tTimerProperties & props) inline explicit
Definition at line 73 of file Timer.h.
References CKernelMPI::CreateTimer(), and kInvalidTimerHndl.
COneShotTimer::~COneShotTimer () inline
Definition at line 81 of file Timer.h.
References CKernelMPI::DestroyTimer().
Member Function Documentation
tErrType COneShotTimer::GetTimerElapsedTimeInMilliSec (U32 * ms) const inline
Definition at line 113 of file Timer.h.
References CKernelMPI::GetTimerElapsedTime(), and kNoErr.
tTimerHndl COneShotTimer::GetTimerHndl () const inline
Definition at line 87 of file Timer.h.
tErrType COneShotTimer::GetTimerRemainingTimeInMilliSec (U32 * ms) const inline
Definition at line 122 of file Timer.h.
References CKernelMPI::GetTimerRemainingTime(), kNoErr, kTimerEventPriority, and LF_END_BRIO_NAMESPACE.
void COneShotTimer::Pause (saveTimerSettings & saveValue) inline
Definition at line 101 of file Timer.h.
References CKernelMPI::PauseTimer().
void COneShotTimer::Resume (saveTimerSettings & saveValue) inline
Definition at line 107 of file Timer.h.
References CKernelMPI::ResumeTimer().
void COneShotTimer::Start (const tTimerProperties & props) inline
Definition at line 93 of file Timer.h.
References CKernelMPI::StartTimer().
The documentation for this class was generated from the following file:
System/Include/Timer.h