#-----------------------------------------------------------------------------
# Brio/System/Core/RsrcMgr
#-----------------------------------------------------------------------------
Import('*')

mytarget = 'Resource'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
sources = FindModuleSources(Dir('.'))
libs	= ['']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
#TODO: add any compiler flag customizations here		
myenv = env.Copy()
mymodule = MakeMyModule(myenv, mytarget, sources, libs, 0)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(mytarget, [], libs, myenv)

Return('mymodule')
