#-----------------------------------------------------------------------------
# Brio/System/Resource
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

module_name	= 'Resource'
mpi_name	= module_name + 'MPI'
sysmpi_name	= 'System' + module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
modsrcs		= FindModuleSources(Dir('.'), vars)
mpisrcs		= [File('PublicMPI/ResourceMPI.cpp').abspath]
modlibs		= ['EventMPI', 'KernelMPI', 'DebugMPI']
mpilibs		= ['ModuleMPI']


#-----------------------------------------------------------------------------
# Setup extended mpi source files
#-----------------------------------------------------------------------------
sysmpisrcs	= [File('PublicMPI/SystemResourceMPI.cpp').abspath]

						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
mymodule	= MakeMyModule(myenv, module_name, modsrcs, modlibs, kBuildModule, vars)
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)
sysmpi		= MakeMyModule(myenv, sysmpi_name, sysmpisrcs, mpilibs + ['ResourceMPI'], kBuildPrivMPI, vars)
Depends(mympi, mymodule)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
RunMyTests(module_name, [], mpilibs + ['EventMPI','DebugMPI'], myenv, vars)


Return('mymodule', 'mympi', 'sysmpi')
