#-----------------------------------------------------------------------------
# Brio/System/Emulation
#-----------------------------------------------------------------------------
Import('*')

mpi_name = 'Emulation'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
mpisrcs		= FindModuleSources(Dir('.'))
mpilibs		= []
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Copy()
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, 1)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
#RunMyTests(module_name, [], mpilibs, myenv)

dummy = []
Return('dummy', 'mympi')
