#-----------------------------------------------------------------------------
# Brio/System/Emulation
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

mpi_name = 'Emulation'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
mpisrcs		= Glob('*.cpp')
mpilibs		= []
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Clone()
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
#if not vars['is_publish']:
#	RunMyTests(module_name, [], mpilibs, myenv, vars)
targets = mympi or []
Return('targets')
