#-----------------------------------------------------------------------------
# Brio/System/Emulation
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

mpi_name = 'Emulation'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
mpisrcs		= FindModuleSources(Dir('.'), vars)
mpilibs		= []
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Clone()
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
#if not vars['is_publish']:
#	RunMyTests(module_name, [], mpilibs, myenv, vars)

dummy = []
Return('dummy', 'mympi')
