"""
Lightning Example Game SConscript file.
"""

import os
import CopyTree

Import('env')
myEnv = env.Clone()     #clone this, so we're not changing the original

libname = 'BrioCube'     #env_vars['tld']

if env['cpu']:
	#global libs
	sources = Glob(os.path.join('*.cpp')) #this should get everything in subdirectories
	
	# Set up targets
	myEnv.Append(CPPPATH = ['Include'])
	
	myResources = CopyTree.CopyTree(myEnv, Dir(os.path.join('#', 'apprsrc')).abspath, env['install_dir'].abspath)
	myModule = myEnv.Program(os.path.join(env['install_dir'].abspath, libname), sources, SHLIBPREFIX='')
	env['targets'] += myModule
	env['targets'] += myResources

