"""
LF Example Game SConscript file.
"""

import os
import CopyTree

Import('env')
myEnv = env.Clone()     #clone this, so we're not changing the original

libname = 'App'     #env_vars['tld']

if env['cpu']:
	#global libs
	sources = Glob(os.path.join('Src', '*.cpp')) #this should get everything in subdirectories
	
	# Set up targets
	myEnv.Append(CPPPATH = ['Include'])
	myEnv.Append(LIBS = ['ImageIO'])
	myEnv.Append(LIBS = ['GLESv1_CM', 'EGL'])
	
	if env['cpu'] == 'x86':
		myEnv.Append(LIBPATH = [os.path.join(os.environ['HOME'], 'emuroot/LF/Base/lib')])
		myEnv.Append(LIBPATH = [os.path.join(os.environ['HOME'], 'emuroot/LF/Base/Brio/lib')])



	myResources = CopyTree.CopyTree(myEnv, Dir(os.path.join('#', 'apprsrc')).abspath, env['install_dir'].abspath)
	myModule = myEnv.SharedLibrary(os.path.join(env['install_dir'].abspath, libname), sources, SHLIBPREFIX='')
	env['targets'] += myModule
	env['targets'] += myResources

