#-----------------------------------------------------------------------------
# Brio/System/USBDevice
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
Import('*')

module_name	= 'USBDevice'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
mpisrcs		= FindMPISources(Dir('.'), vars)
mpilibs		= ['Utility']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Clone()
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI, vars)

#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
if not vars['is_publish']:
	RunMyTests(module_name, [], mpilibs + ['EventMPI'], myenv, vars)

Return('mympi')
