#-----------------------------------------------------------------------------
# Brio/System/USBDevice
#-----------------------------------------------------------------------------
from Etc.Tools.SConsTools.Priv.LfUtils import *
import os

Import('env')

module_name	= 'USBDevice'
mpi_name	= module_name + 'MPI'

#-----------------------------------------------------------------------------
# Setup module source files and libraries
#-----------------------------------------------------------------------------
mpisrcs		= Glob(os.path.join('PublicMPI', '*.cpp'))
mpilibs		= ['Utility']
						
#-----------------------------------------------------------------------------
# Modify the build environment and build the module
#-----------------------------------------------------------------------------
myenv		= env.Clone()
myenv.Append(CPPPATH=['Include'])
mympi		= MakeMyModule(myenv, mpi_name, mpisrcs, mpilibs, kBuildMPI)

targets = mympi or []
#-----------------------------------------------------------------------------
# Modify the build environment and build and run the unit tests
#-----------------------------------------------------------------------------
if env['buildtests']:
	if env['cpu'] != 'x86':
		targets.append(RunMyTests(module_name, [], mpilibs + ['EventMPI', 'ButtonMPI'], myenv))
	else:
		print "WARNING: USBDevice test disabled in emulation until fixed!"

Return('targets')
